### PR TITLE
Fix: Sort phone number by name with ❤️

### PR DESCRIPTION
**Pull request by imirazimi**

### CODE REVIEW

**Comment by imirazimi** [comment]
Hi, I'm back!

**Review by BaseMax — CHANGES_REQUESTED** [review]
# command-line-arguments
.\filterer.go:81:2: sortedPhoneNumbers declared but not used
.\filterer.go:114:15: cannot use key (variable of type []reflect.Value) as type []string in argument to sort.Strings
.\filterer.go:117:7: cannot use v (variable of type reflect.Value) as type string in map index
.\filterer.go:117:25: cannot use key[i] (variable of type reflect.Value) as type string in map index

**Review by BaseMax — CHANGES_REQUESTED** [review]
C:\Users\Max\PhoneNumberFilterer>go run filterer.go
# command-line-arguments
.\filterer.go:80:2: sortedPhoneNumbers declared but not used
.\filterer.go:119:25: undefined: key

**Review by BaseMax — APPROVED** [review]

**Comment by BaseMax** [comment]
Great job. thanks

**Pull request merged**
